# Generated by Django 5.0.1 on 2025-08-07 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wimm', '0001_initial'),
        ('modules_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='TR', max_length=2)),
                ('warehouse_type', models.CharField(choices=[('physical', 'Physical Warehouse'), ('virtual', 'Virtual Location'), ('store', 'Retail Store'), ('transit', 'In Transit'), ('customer', 'Customer Location'), ('supplier', 'Supplier Location')], default='physical', max_length=20)),
                ('manager', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location_type', models.CharField(choices=[('rack', 'Rack'), ('shelf', 'Shelf'), ('bin', 'Bin'), ('floor', 'Floor'), ('refrigerated', 'Refrigerated'), ('frozen', 'Frozen'), ('hazmat', 'Hazardous Materials')], default='shelf', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='wims.stocklocation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='wims.warehouse')),
            ],
            options={
                'ordering': ['warehouse', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('count_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('count_type', models.CharField(choices=[('full', 'Full Count'), ('cycle', 'Cycle Count'), ('spot', 'Spot Check')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_counts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='wims.warehouse')),
            ],
            options={
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='ItemSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_code', models.CharField(blank=True, max_length=50)),
                ('supplier_item_code', models.CharField(blank=True, max_length=50)),
                ('supplier_item_name', models.CharField(blank=True, max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('lead_time_days', models.IntegerField(default=0)),
                ('min_order_quantity', models.DecimalField(decimal_places=4, default=1, max_digits=20)),
                ('order_multiple', models.DecimalField(decimal_places=4, default=1, max_digits=20)),
                ('is_preferred', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='modules_core.item')),
            ],
            options={
                'ordering': ['item', 'priority', 'supplier_name'],
                'unique_together': {('item', 'supplier_name')},
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('counted_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules_core.item')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wims.stockcount')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wims.stocklocation')),
            ],
            options={
                'ordering': ['item__name'],
                'unique_together': {('stock_count', 'item', 'location', 'batch_number', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('production', 'Production'), ('consumption', 'Consumption'), ('return', 'Return'), ('damage', 'Damage'), ('expired', 'Expired')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='wims.stocklocation')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='wimm.invoice')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='wimm.invoiceitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='modules_core.item')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='wims.stocklocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='wims.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='wims.warehouse')),
            ],
            options={
                'ordering': ['-movement_date'],
                'indexes': [models.Index(fields=['item', '-movement_date'], name='wims_stockm_item_id_d72153_idx'), models.Index(fields=['movement_type', '-movement_date'], name='wims_stockm_movemen_4b23f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('min_stock_level', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('max_stock_level', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('reorder_point', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('reorder_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='modules_core.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='wims.stocklocation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='wims.warehouse')),
            ],
            options={
                'ordering': ['item__name', 'warehouse__name'],
                'indexes': [models.Index(fields=['item', 'warehouse'], name='wims_stocki_item_id_aa36ee_idx'), models.Index(fields=['expiry_date'], name='wims_stocki_expiry__438acc_idx')],
                'unique_together': {('item', 'warehouse', 'batch_number', 'serial_number')},
            },
        ),
    ]
