# Generated by Django 5.0.1 on 2025-08-19 09:22

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=50, unique=True)),
                ('retention_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('archive_enabled', models.BooleanField(default=False)),
                ('archive_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Log retention policies',
                'db_table': 'log_retention_policies',
            },
        ),
        migrations.CreateModel(
            name='LogAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hour', models.DateTimeField(unique=True)),
                ('debug_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('category_counts', models.JSONField(default=dict)),
                ('active_users', models.IntegerField(default=0)),
                ('total_actions', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(blank=True, null=True)),
                ('p95_response_time', models.FloatField(blank=True, null=True)),
                ('p99_response_time', models.FloatField(blank=True, null=True)),
                ('top_errors', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'log_aggregations',
                'ordering': ['-date_hour'],
                'indexes': [models.Index(fields=['-date_hour'], name='log_aggrega_date_ho_5ba10c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='activity_lo_timesta_668a13_brin'), models.Index(fields=['user', 'timestamp'], name='activity_lo_user_id_e40ffe_idx'), models.Index(fields=['action', 'timestamp'], name='activity_lo_action_fe3d88_idx'), models.Index(fields=['module', 'timestamp'], name='activity_lo_module_2f7591_idx'), django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='activity_lo_metadat_f6a75a_gin')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('debug', 'debug'), ('info', 'info'), ('warning', 'warning'), ('error', 'error'), ('critical', 'critical')], default='info', max_length=10)),
                ('category', models.CharField(choices=[('auth', 'authentication'), ('api', 'api calls'), ('admin', 'administration'), ('user', 'user actions'), ('system', 'system events'), ('security', 'security events'), ('payment', 'payment events'), ('module', 'module actions'), ('database', 'database operations'), ('performance', 'performance metrics')], max_length=20)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, max_length=100)),
                ('function', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('exception_type', models.CharField(blank=True, max_length=100)),
                ('traceback', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_logs',
                'ordering': ['-timestamp'],
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='system_logs_timesta_a91769_brin'), models.Index(fields=['level', 'category'], name='system_logs_level_e48114_idx'), models.Index(fields=['user', 'timestamp'], name='system_logs_user_id_942324_idx'), django.contrib.postgres.indexes.GinIndex(fields=['extra_data'], name='system_logs_extra_d_6355b1_gin')],
            },
        ),
    ]
