# Generated by Django 5.0.1 on 2025-08-19 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitaire', '0003_rename_solitaire_s_session_f0e3e1_idx_solitaire_s_session_b83e8d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolitaireGameDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('deck_seed', models.CharField(max_length=100)),
                ('deck_configuration', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deck_id'], name='solitaire_s_deck_id_b5d677_idx'), models.Index(fields=['created_at'], name='solitaire_s_created_a990d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolitaireMultiplayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer_games', to='solitaire.solitairegamedeck')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer_games_as_player1', to='solitaire.solitaireplayer')),
                ('player1_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer_as_player1', to='solitaire.solitairegamesession')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer_games_as_player2', to='solitaire.solitaireplayer')),
                ('player2_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer_as_player2', to='solitaire.solitairegamesession')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_multiplayer_games', to='solitaire.solitaireplayer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
