# Generated by Django 5.0.1 on 2025-08-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitaire', '0004_solitairegamedeck_solitairemultiplayergame'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolitaireMoveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('from_pile_type', models.CharField(choices=[('stock', 'Stock'), ('waste', 'Waste'), ('tableau', 'Tableau'), ('foundation', 'Foundation')], max_length=20)),
                ('from_pile_index', models.IntegerField(blank=True, null=True)),
                ('to_pile_type', models.CharField(choices=[('stock', 'Stock'), ('waste', 'Waste'), ('tableau', 'Tableau'), ('foundation', 'Foundation')], max_length=20)),
                ('to_pile_index', models.IntegerField(blank=True, null=True)),
                ('cards', models.JSONField()),
                ('num_cards', models.IntegerField(default=1)),
                ('score_before', models.IntegerField(default=0)),
                ('score_after', models.IntegerField(default=0)),
                ('score_change', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_since_start', models.IntegerField(default=0)),
                ('time_since_last_move', models.IntegerField(default=0)),
                ('is_undo', models.BooleanField(default=False)),
                ('is_auto_move', models.BooleanField(default=False)),
                ('revealed_card', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_history', to='solitaire.solitairegamesession')),
            ],
            options={
                'ordering': ['session', 'move_number'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='solitaire_s_session_f0df23_idx'), models.Index(fields=['session', 'move_number'], name='solitaire_s_session_8e96b1_idx')],
                'unique_together': {('session', 'move_number')},
            },
        ),
    ]
